name: Build Android

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses and install components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" "ndk;26.1.10909125"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android

      - name: Install Tauri CLI
        run: npm i -D @tauri-apps/cli@^2

      - name: Install frontend dependencies
        run: npm ci

      - name: Generate icons from flymd.png
        run: npx tauri icon ./flymd.png

      - name: Init Android project (if missing)
        run: |
          if [ ! -d "src-tauri/gen/android" ]; then
            npm run tauri:android:init -- --ci
          fi

      - name: Build Android (release)
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_SDK_ROOT }}/ndk/26.1.10909125
        run: npm run tauri:android:build -- --release

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flymd-Android
          path: |
            src-tauri/gen/android/app/build/outputs/apk/**/*.apk
            src-tauri/gen/android/app/build/outputs/bundle/**/*.aab
          if-no-files-found: warn
